name: pms

services:
  # qBittorrent bittorrent client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=9000
      - TORRENTING_PORT=54321
    ports:
      - 9000:9000
      - 54321:54321
    volumes:
      - qbittorrent-config:/config
      - /share/Downloads:/data/downloads

  # SABnzbd usenet downloader
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - sabnzbd-config:/config
      - /share/Downloads:/data/downloads
      - /share/Backup/sabnzbd:/backup
    ports:
      - 9001:8080

  # Jackett torrent indexer
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 9002:9117
    volumes:
      - jackett-config:/config
      - /share/Downloads:/data/downloads

  # Postgres database
  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # pgAdmin web interface for Postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 9003:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

networks:
  default:
    name: pms

volumes:
  qbittorrent-config:
    driver: local
  sabnzbd-config:
    driver: local
  jackett-config:
    driver: local
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
