name: pms

services:
  # qBittorrent bittorrent client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=9000
      - TORRENTING_PORT=54321
    ports:
      - 9000:9000
      - 54321:54321
    volumes:
      - qbittorrent-config:/config
      - ${HOST_DOWNLOADS}:/data/downloads

  # SABnzbd usenet downloader
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - sabnzbd-config:/config
      - ${HOST_DOWNLOADS}:/data/downloads
      - ${HOST_BACKUP}/sabnzbd:/backup
    ports:
      - 9001:8080

  # Jackett torrent indexer
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 9002:9117
    volumes:
      - jackett-config:/config

  # Postgres database
  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${ADMIN_PASSWORD}
      - TZ=${TZ}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # pgAdmin web interface for Postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - 9003:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  # Sonarr TV show manager
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - postgres
      - qbittorrent
      - sabnzbd
      - jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 9004:8989
    volumes:
      - sonarr-config:/config
      - ${HOST_DOWNLOADS}:/data/downloads
      - ${HOST_MEDIA}/tv:/data/media/tv
      - ${HOST_BACKUP}/sonarr:/backup

  # Radarr movie manager
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - postgres
      - qbittorrent
      - sabnzbd
      - jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 9005:7878
    volumes:
      - radarr-config:/config
      - ${HOST_DOWNLOADS}:/data/downloads
      - ${HOST_MEDIA}/movies:/data/media/movies
      - ${HOST_BACKUP}/radarr:/backup

networks:
  default:
    name: pms

volumes:
  qbittorrent-config:
    driver: local
  sabnzbd-config:
    driver: local
  jackett-config:
    driver: local
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  sonarr-config:
    driver: local
  radarr-config:
    driver: local
