name: pms

services:
  # qBittorrent bittorrent client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=9000
      - TORRENTING_PORT=54321
    ports:
      - 9000:9000
      - 54321:54321
    volumes:
      - qbittorrent-config:/config
      - /share/Downloads:/data/downloads

  # SABnzbd usenet downloader
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - sabnzbd-config:/config
      - /share/Downloads:/data/downloads
      - /share/Backup/sabnzbd:/backup
    ports:
      - 9001:8080

  # Jackett torrent indexer
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 9002:9117
    volumes:
      - jackett-config:/config
      - /share/Downloads:/data/downloads

networks:
  default:
    name: pms

volumes:
  qbittorrent-config:
    driver: local
  sabnzbd-config:
    driver: local
  jackett-config:
    driver: local
