name: pms

services:
  # qBittorrent bittorrent client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=9000
      - TORRENTING_PORT=54321
    ports:
      - 9000:9000
      - 54321:54321
    volumes:
      - qbittorrent-config:/config
      - /share/Downloads:/data/downloads

networks:
  default:
    name: pms

volumes:
  qbittorrent-config:
    driver: local
