name: pms

services:
  # qBittorrent bittorrent client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=54321
    ports:
      - 9000:8080
      - 54321:54321
    volumes:
      - /share/Config/qbittorrent:/config
      - /share/Downloads:/data/downloads

networks:
  default:
    name: pms

volumes:
  qbittorrent-config:
    driver: local
